#! /usr/bin/bash

# weka-install - install weka on bootup of a new server, and configure misc items that can't be done in kickstart
# working dir should be /opt/wekabits   (if put in /opt/weka, it would be removed with wekawhacker)

#pushd ..
#tar xvf wekabits/local-weka-home.tgz
#tar xvf wekabits/weka-mon.tgz
#tar xvf wekabits/snaptool.tgz
#tar xvf wekabits/tools.tgz
#tar xvf wekabits/wms-gui.tgz

#cp /opt/wekabits/wms-gui.service /etc/systemd/system
#systemctl enable --now wms-gui.service

# install weka-mon
#pushd weka-mon
#./install.sh
#sed -i 's,${PWD},/opt/weka-mon,' docker-compose.yml
#popd

# prep local weka home
#pushd local-weka-home/wekahome_offline
#./update_config.sh
#popd

#popd

### other weka installation items

# configure firewall
firewall-cmd --set-default-zone=public  # other options are set in the kickstart

# set up ssh keys for root and weka (predefined in subdirs of current directory)
echo Working in $PWD...
mkdir ~root/.ssh
chmod 700 ~root/.ssh
cp root/* ~root/.ssh
chown -R root ~root/.ssh
chmod 600 ~root/.ssh/id_rsa

mkdir ~weka/.ssh
chmod 700 ~weka/.ssh
cp weka/* ~weka/.ssh
chown -R weka ~weka/.ssh
chmod 600 ~weka/.ssh/id_rsa

# this is a bit of a hack - there should be an RPM somewhere in the repo that sets this stuff?
# should we change the cockpit port from 9090 to something else?
#mkdir -p /usr/share/cockpit/branding/weka
#cp weka-cockpit-branding/* /usr/share/cockpit/branding/weka

echo 'exclude=kernel* rocky-release*' >> /etc/dnf/dnf.conf

# disable systemd unit that starts this script so it never runs again
systemctl disable weka-firstboot.service

# start cockpit
#systemctl enable --now cockpit.socket

# Turn off account management in Cockpit (so it's more secure)
#cp override.json /usr/share/cockpit/users/
# copy our local filesystem overrides into place..
#cp -r usr /

# install motd (for betas, it's a warning, otherwise a welcome message)
#cp motd /etc/

firewall-cmd --add-port 3000/tcp --add-port 8151/tcp --add-port 8090/tcp --add-port 443/tcp --add-port 80/tcp --permanent
firewall-cmd --remove-port=14000-15000/tcp
# add ports for ansible-install
firewall-cmd --add-port 7860/tcp --add-port 8060/tcp
firewall-cmd --reload

