#! /usr/bin/env bash

if [ ! -d venv ]; then 
	/usr/bin/python3.11 -m venv venv

	source venv/bin/activate
	# *.* excludes the makefile. :facepalm:
	pip3 install local_wheels/*.*
else
	source venv/bin/activate
fi

streamlit run Landing_Page.py
