#! /usr/bin/env bash

export PATH=$PATH:/opt/wekahome/current/bin:/opt/k3s/bin
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

if [ ! -d venv ]; then 
	/usr/bin/python3.11 -m venv venv

	source venv/bin/activate
	# *.* excludes the makefile. :facepalm:
	pip3 install local_wheels/*.*
else
	source venv/bin/activate
fi

streamlit run Landing_Page.py
